spring.application.name=SpringEcom
spring.datasource.url=jdbc:postgresql://localhost:5432/upskill
spring.datasource.username=venkatasaiesampalli
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true